### ISSUE TITLE
Flutter web

### ISSUE THREAD

**Issue by ChristopheChanteur** [RoundedInfinity/animated_emoji#1]
Hi, 
Thank you for this great package, 
It works well on device platforms, but it says it supports also Flutter Web, but it seems it isn't the case.
please see attached the screenshot error I have on the chrome web simulator.
I have tried deploying my flutter webapp also and tried the app on a device's via weblink, and it doesn't work on the flutter webapp.

Can you check this package on Flutter web please?

The Error on Flutter Web
<img width="576" alt="image" src="https://user-images.githubusercontent.com/53230125/234896337-aa45ee8e-309f-4865-85e6-52acba4545dd.png">

The same Code working perfectly on device platform (ios, android...) 
<img width="408" alt="image" src="https://user-images.githubusercontent.com/53230125/234897350-c7bee5b0-f021-424d-992b-f0b26428e5ea.png">

regards, 
Chris

**Comment by ChristopheChanteur** [comment]
update: after some checks, the Widget partially works on web, 
if I give it an errorWidget property, it displays that widget on Flutter web, so I suppose the issue is the animated emoji part needs to be looked at

**Comment by ChristopheChanteur** [comment]
last update: I tried to fork your package and update it with the latest Lottie version - and the error still exists.
I also tried to only use the Lottie package and link it to the json url your package points to.
and it still is the same issue.
I think the issue may either lie with Lottie, or with the json at the url provided ...

hope you can find a way to solve it because your package is awesome

**Comment by RoundedInfinity** [comment]
Hey, thanks for the feedback, 

I've looked into this issue and I think it does not work because of the [CORS](https://docs.flutter.dev/platform-integration/web/web-images) settings of the Noto Emoji Website. Just fetching the emoji url with `http.get` throws an error on flutter web. 

I'm planning on adding support for loading the emojis from the local assets. That would fix the problem, but I'm not quite sure on how to tackle this.

**Comment by ChristopheChanteur** [comment]
you're welc.

Thanks for looking into this for us.
Looking forward to the update

**Comment by hsbijarniya** [comment]
#3 implemented
