### ISSUE TITLE
Upgrade lottie version from 2.7.0 to 3.0.0

### ISSUE THREAD

**Issue by abdullah-cse** [RoundedInfinity/animated_emoji#11]
As this package depends on lotties old version(2.7.0), can't use it.

In my project I'm using latest version of [lottie](https://pub.dev/packages/lottie), whenever trying to add this package(animated_emoji), version solving fails. The LOG is 
```
Resolving dependencies...
Because demoapp depends on animated_emoji ^3.0.0 which depends on lottie ^2.7.0, lottie ^2.7.0 is required.
So, because demoapp depends on lottie ^3.0.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on lottie: flutter pub add lottie:^2.7.0
exit code 1
```
But downgrading lottie isn't possible in my cases, because lottie's latest version has my advantage over older version.

So, please upgrade lotties version in this package(animated_emoji)

**Comment by RoundedInfinity** [comment]
Done. Newest version now uses lottie 3.0.0.
