### ISSUE TITLE
Include svgs in package

### ISSUE THREAD

**Issue by kwellman** [RoundedInfinity/animated_emoji#12]
It would be useful have access to the non-animated version of each emoji (e.g. the svgs in the https://github.com/googlefonts/noto-emoji repository) through this package. Using something like ```AnimatedEmoji(size: 40, AnimatedEmojis.mindBlown, source: AnimatedEmojiSource.asset, animate: false))``` doesn't represent the emojis well in, for example, a dialog that allows the user to pick which animated emoji to use.

**Comment by RoundedInfinity** [comment]
You can use the Noto Emoji font to get the non-animated emojis. You could also use an AnimationController to set the current value of the animation without actually animating the emoji to a value where the emoji is represented as you like.

Sorry for the late reply, I hope this helps.

**Comment by kwellman** [comment]
Thanks for the update. I ended up using https://github.com/googlefonts/noto-emoji as assets to get the non-animated emojis. 👍
