### ISSUE TITLE
Please add all new emoji's from Noto Emoji

### ISSUE THREAD

**Issue by OutdatedGuy** [RoundedInfinity/animated_emoji#2]
The package doesn't have emojis like [muscle](https://googlefonts.github.io/noto-emoji-animation/?icon.query=:muscle:) and many others.

Please add all the animated emojis available from [noto emoji](https://googlefonts.github.io/noto-emoji-animation/) in the latest version.

**Comment by hsbijarniya** [comment]
added more emoji total as of now 344

see #3
