### ISSUE TITLE
Is there a lower limit for the size of the emojis? 

### ISSUE THREAD

**Issue by krisboyy** [RoundedInfinity/animated_emoji#4]
I tried ramping up the size from 20 to 60. No change in the appearance of the emoji.

**Comment by RoundedInfinity** [comment]
The emojis can only get as big as their parents, even if the size is bigger. So wrapping a AnimatedEmoji in a SizedBox with width and height of 40 limits the size of the emoji to 40, even if it is set to something larger.

Hope this answers your question
