### ISSUE TITLE
Is there any way to control the stop frame when animate is set to false ?

### ISSUE THREAD

**Issue by louislamme** [RoundedInfinity/animated_emoji#5]
When I set the animation to false it shows the same graphic of "broken-heart" and "red-heart", is there a solution to set the default "frame"?

This is the Broken-heart icon from official [https://googlefonts.github.io/noto-emoji-animation/](url)
![Screenshot 2023-08-11 at 5 11 23 PM](https://github.com/RoundedInfinity/animated_emoji/assets/9133226/8477c08c-31ab-4525-9f5b-cb02fbd42366)

**Comment by cory-brown** [comment]
For default frame of the emoji, you just need select the emoji you want and change your font to "Noto Color Emoji"

For "red-heart" you can use the following:

`Text('♥️',style: GoogleFonts.notoColorEmoji(fontSize: 60))`

And for "broken-heart"

`Text('💔',style: GoogleFonts.notoColorEmoji(fontSize: 60))`

You can copy them from: https://fonts.google.com/noto/specimen/Noto+Color+Emoji/glyphs?coloronly=true

Also, you will need to add the Google Fonts package to you project: https://pub.dev/packages/google_fonts

**Comment by RoundedInfinity** [comment]
Yeah, that's a great solution for static emojis.

If you want to have full control of which frames are shown, you could use an `Animation` for the `controller` argument instead of the `animate` argument (for example, an animation that starts at 0.2 instead of 0 to start at a different frame).

**Comment by louislamme** [comment]
Thank you for your suggestions.
I ended up using svg images to solve this because the file size of notoColorEmoji was too large in my case (I only needed 10-20 emoji).
