### ISSUE TITLE
Flutter web some animation are failing

### ISSUE THREAD

**Issue by sebastienvermeille** [RoundedInfinity/animated_emoji#6]
Hi,

I figure some issues using the library on flutter web:

sun glasses cool guy:
```yaml
  assets:
    - packages/animated_emoji/lottie/sunglassesFace.json
 ```

```dart
    return AnimatedEmoji(
      AnimatedEmojis.sunglassesFace,
      size: 128,
      repeat: true,
    );
```
![2023-08-16_17-20](https://github.com/RoundedInfinity/animated_emoji/assets/4329594/4cd22672-1e6b-48af-801b-0570ce0f5eaf)

rocket:
```yaml
  assets:
    - packages/animated_emoji/lottie/rocket.json
 ```

```dart
    return AnimatedEmoji(
      AnimatedEmojis.rocket,
      size: 128,
      repeat: true,
    );
```

![2023-08-16_17-23](https://github.com/RoundedInfinity/animated_emoji/assets/4329594/97e2f435-0dd1-40c6-9e4b-4b487be2a738)

The reported error is:
```
Flutter Web does not support the blend mode: BlendMode.clear
Another exception was thrown: PersistedScene: is in an unexpected state.
Another exception was thrown: PersistedScene: is in an unexpected state.
Another exception was thrown: PersistedScene: is in an unexpected state.
Another exception was thrown: PersistedScene: is in an unexpected state.
```

However `clapDark` animation works perfectly fine.

Do you have any idea about that ?

Thank you! (The lib looks really gorgeous it will give a lot of fresh to my app thank you for that!)

**Comment by RoundedInfinity** [comment]
Looks like this is only the case when using HTML as the default renderer because it does not support `BlendMode.clear`.

This should work when using [CanvasKit](https://docs.flutter.dev/platform-integration/web/renderers) as the default renderer.
