### ISSUE TITLE
Is there any way of getting the emoji by it's camelCase name?

### ISSUE THREAD

**Issue by DaryeDev** [RoundedInfinity/animated_emoji#7]
I'm trying to get the AnimatedEmojiData dynamically, but can't figure out how without a massive switch statement. 
Is there any way to transform the camelCase name of the emojis to their AnimatedEmojiData Object?

**Comment by fahidsarker** [comment]
Looking at the source code, I don't think it is possible to get by camelCase name (unless using reflection). I am not sure what your exact use-case is but I sent a PR [here](https://github.com/RoundedInfinity/animated_emoji/pull/8) that can get you the animated emoji from an unicode emoji character like '❤️'. Perhaps you can use some other libs to convert the name to the emoji character and then use my PR to achieve what you want. Happy coding :-)

**Comment by RoundedInfinity** [comment]
Added the `fromName` function in the newest version that does exactly this 🚀
