### ISSUE TITLE
noto-emoji-animation has new emojis available

### ISSUE THREAD

**Issue by dfilter** [RoundedInfinity/animated_emoji#9]
I have added some of the missing emojis please see my fork [here](https://github.com/dfilter/animated_emoji)

I'm not sure which other emojis are missing.

**Comment by rbozan** [comment]
At first glance some are definitely still missing like the bicycle emoji.

**Comment by dfilter** [comment]
> At first glance some are definitely still missing like the bicycle emoji and cloud with rain.
> 
> I'm not sure whether the library uses this but we could perhaps use https://github.com/googlefonts/emoji-metadata/blob/main/emoji_15_1_ordering.json to retrieve all the animated emojis at once.

I've added the rest of the missing ones

**Comment by rbozan** [comment]
> > At first glance some are definitely still missing like the bicycle emoji and cloud with rain.
> > I'm not sure whether the library uses this but we could perhaps use [googlefonts/emoji-metadata@`main`/emoji_15_1_ordering.json](https://github.com/googlefonts/emoji-metadata/blob/main/emoji_15_1_ordering.json?rgh-link-date=2023-11-16T19%3A00%3A29Z) to retrieve all the animated emojis at once.
> 
> I've added the rest of the missing ones

Well the Lottie files are missing though: https://github.com/dfilter/animated_emoji/tree/main/lib/lottie

**Comment by dfilter** [comment]
> Well the Lottie files are missing though: https://github.com/dfilter/animated_emoji/tree/main/lib/lottie

Good catch 🤦‍♂️

**Comment by dfilter** [comment]
added the lottie files

**Comment by rbozan** [comment]
I'm not sure if the author of the package did this all manually. 

One thing I noticed in your repo,

"wrappedGift": "wrappedGift",

https://github.com/dfilter/animated_emoji/blob/main/lib/emojis.dart#L786

But thanks, I will use your repo until this package includes the new emojis :)

**Comment by RoundedInfinity** [comment]
They were added manually. I'm currently working on a bigger update with a generator script that should fix this.

**Comment by dfilter** [comment]
> I'm not sure if the author of the package did this all manually.
> 
> One thing I noticed in your repo,
> 
> "wrappedGift": "wrappedGift",
> 
> https://github.com/dfilter/animated_emoji/blob/main/lib/emojis.dart#L786
> 
> But thanks, I will use your repo until this package includes the new emojis :)
> 
> Edit: Also somehow these 2 seem to be mixed somewhere:
> 
> https://github.com/dfilter/animated_emoji/blob/main/lib/emojis.dart#L813-L814

Thanks for all the help man.

**Comment by RoundedInfinity** [comment]
All emojis should now be added to the package (hopefully)
